/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalkthroughRouteImport } from './routes/walkthrough'
import { Route as VulnerableRouteImport } from './routes/vulnerable'
import { Route as SecureRouteImport } from './routes/secure'
import { Route as LabRouteImport } from './routes/lab'
import { Route as DefenseRouteImport } from './routes/defense'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AttacksRouteImport } from './routes/attacks'
import { Route as IndexRouteImport } from './routes/index'

const WalkthroughRoute = WalkthroughRouteImport.update({
  id: '/walkthrough',
  path: '/walkthrough',
  getParentRoute: () => rootRouteImport,
} as any)
const VulnerableRoute = VulnerableRouteImport.update({
  id: '/vulnerable',
  path: '/vulnerable',
  getParentRoute: () => rootRouteImport,
} as any)
const SecureRoute = SecureRouteImport.update({
  id: '/secure',
  path: '/secure',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DefenseRoute = DefenseRouteImport.update({
  id: '/defense',
  path: '/defense',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AttacksRoute = AttacksRouteImport.update({
  id: '/attacks',
  path: '/attacks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attacks': typeof AttacksRoute
  '/dashboard': typeof DashboardRoute
  '/defense': typeof DefenseRoute
  '/lab': typeof LabRoute
  '/secure': typeof SecureRoute
  '/vulnerable': typeof VulnerableRoute
  '/walkthrough': typeof WalkthroughRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attacks': typeof AttacksRoute
  '/dashboard': typeof DashboardRoute
  '/defense': typeof DefenseRoute
  '/lab': typeof LabRoute
  '/secure': typeof SecureRoute
  '/vulnerable': typeof VulnerableRoute
  '/walkthrough': typeof WalkthroughRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attacks': typeof AttacksRoute
  '/dashboard': typeof DashboardRoute
  '/defense': typeof DefenseRoute
  '/lab': typeof LabRoute
  '/secure': typeof SecureRoute
  '/vulnerable': typeof VulnerableRoute
  '/walkthrough': typeof WalkthroughRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attacks'
    | '/dashboard'
    | '/defense'
    | '/lab'
    | '/secure'
    | '/vulnerable'
    | '/walkthrough'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attacks'
    | '/dashboard'
    | '/defense'
    | '/lab'
    | '/secure'
    | '/vulnerable'
    | '/walkthrough'
  id:
    | '__root__'
    | '/'
    | '/attacks'
    | '/dashboard'
    | '/defense'
    | '/lab'
    | '/secure'
    | '/vulnerable'
    | '/walkthrough'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttacksRoute: typeof AttacksRoute
  DashboardRoute: typeof DashboardRoute
  DefenseRoute: typeof DefenseRoute
  LabRoute: typeof LabRoute
  SecureRoute: typeof SecureRoute
  VulnerableRoute: typeof VulnerableRoute
  WalkthroughRoute: typeof WalkthroughRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/walkthrough': {
      id: '/walkthrough'
      path: '/walkthrough'
      fullPath: '/walkthrough'
      preLoaderRoute: typeof WalkthroughRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vulnerable': {
      id: '/vulnerable'
      path: '/vulnerable'
      fullPath: '/vulnerable'
      preLoaderRoute: typeof VulnerableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secure': {
      id: '/secure'
      path: '/secure'
      fullPath: '/secure'
      preLoaderRoute: typeof SecureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defense': {
      id: '/defense'
      path: '/defense'
      fullPath: '/defense'
      preLoaderRoute: typeof DefenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attacks': {
      id: '/attacks'
      path: '/attacks'
      fullPath: '/attacks'
      preLoaderRoute: typeof AttacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttacksRoute: AttacksRoute,
  DashboardRoute: DashboardRoute,
  DefenseRoute: DefenseRoute,
  LabRoute: LabRoute,
  SecureRoute: SecureRoute,
  VulnerableRoute: VulnerableRoute,
  WalkthroughRoute: WalkthroughRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
